name: Check Fixup Commits

on: workflow_call

jobs:
  check-fixups:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Prevent Fixup Commits
      env:
        TARGET_BRANCH: ${{ github.base_ref }}
        # BASE_SHA=$(git merge-base origin/$TARGET_BRANCH HEAD)
      run: |
        git log origin/$TARGET_BRANCH..HEAD | grep -iE '^[[:blank:]]*fixup|wip|squash' && exit 1 || echo "No temporary commits found"

