name: Check Fixup Commits

on: workflow_call

jobs:
  check-fixups:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Prevent Fixup Commits
      env:
        TARGET_BRANCH: ${{ github.base_ref }}
      run: |
        git log origin/$TARGET_BRANCH..HEAD | grep -ie '^[[:blank:]]*fixup' && exit 1 || echo "No temporary commits found"

