name: Pull Request CI

on: 
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    - ready_for_review

jobs:
  run-commands:
    if: (github.head_ref || github.ref_name) != 'development' && github.event.pull_request.draft == false
    uses: ./.github/workflows/run-commands.yml
    with:
      branch: ${{ github.head_ref || github.ref_name }}

  check-fixups:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/check-fixups.yml
