name: Pull Request CI Runner

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - run-actions
  pull_request:
    types:
      - review_requested
      - labeled

jobs:
  remove-label:
    runs-on: ubuntu-latest
    steps:
      - name: Remove run-actions label
        run: |
          curl -L \
            -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TOKEN_LABELS }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels/run-actions

  run-tests:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'run-actions')
    steps:
      - name: Run tests
        run: echo "Running tests..."
      - name: Check SHA
        run: |
          echo "${{ github.event.pull_request.head.sha || github.event.issue.pull_request.head.sha }}"
          echo "${{ github.base_ref}} -- ${{ github.head_ref }} -- ${{ github.ref }}"

  run-commands:
    if: ${{ (github.head_ref || github.ref_name) != 'development' }}
    uses: ./.github/workflows/run-commands.yml
    with:
      branch: ${{ github.head_ref || github.ref_name }}

  check-fixups:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'run-actions')
    steps:
      - name: Check for fixup commits
        run: echo "Checking for fixup commits..."

