name: Pull Request CI Runner

on:
  repository_dispatch:
    types:
      - run-actions
  pull_request:
    types:
      - review_requested

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: echo "Running tests..."

  check-fixups:
    runs-on: ubuntu-latest
    steps:
      - name: Check for fixup commits
        run: echo "Checking for fixup commits..."

