name: Trigger CI from PR Comment

on:
  issue_comment:
    types: [created]

jobs:
  trigger:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/run-actions')
    runs-on: ubuntu-latest
    # permissions:
    #   contents: read
    #   actions: write
    steps:
      - name: Trigger CI via repository_dispatch
        run: |
          curl -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"event_type": "run-actions"}'

