name: Pull Request CI Runner

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - run-actions
  pull_request:
    types:
      - review_requested
      - labeled

jobs:
  run-tests:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'run-actions')
    steps:
      - name: Run tests
        run: echo "Running tests..."
      - name: Check SHA
        run: echo "${{ github.event.pull_request.head.sha || github.event.issue.pull_request.head.sha }}"

  run-commands:
    if: ${{ (github.head_ref || github.ref_name) != 'development' }}
    uses: ./.github/workflows/run-commands.yml
    with:
      branch: ${{ github.head_ref || github.ref_name }}

  check-fixups:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'run-actions')
    steps:
      - name: Check for fixup commits
        run: echo "Checking for fixup commits..."

