name: Pull Request CI

on:
  pull_request:
    types:
      - review_requested

jobs:
  run-commands:
    if: ${{ (github.head_ref || github.ref_name) != 'development' }}
    uses: ./.github/workflows/run-commands.yml
    with:
      branch: ${{ github.head_ref || github.ref_name }}

  check-fixups:
    uses: ./.github/workflows/check-fixups.yml
